import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillYoutube,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import img3d from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Suhaib's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbysb</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Suhaib Ahmad
            </h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Creative and results-oriented Computer Science fresh graduate
              looking for an opportunity to learn and apply my knowledge in the
              ﬁeld of Web Development and Blockchain Technology. Creative s
              thinker possessing an interest in researching and learning the
              latest development within the industry.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={img3d} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Development and Designing Lorem ipsum dolor sit, amet consectetur
              a dipisicing elit.
              <span className="text-teal-500">
                Dolorum q uod expedita ullam laborum eligendi nulla
              </span>
              a illum, ducimus eveniet iusto consequatur quia! Illum ut expedita
              voluptates sunt, excepturi tenetur at.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Development and Designing Lorem ipsum dolor sit, amet consectetur
              a dipisicing elit.
              <span className="text-teal-500">
                Dolorum q uod expedita ullam laborum eligendi nulla
              </span>
              a illum, ducimus eveniet iusto consequatur quia! Illum ut expedita
              voluptates sunt, excepturi tenetur at.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Development and Designing Lorem ipsum dolor sit, amet consectetur
              a dipisicing elit.
              <span className="text-teal-500">
                Dolorum q uod expedita ullam laborum eligendi nulla
              </span>
              a illum, ducimus eveniet iusto consequatur quia! Illum ut expedita
              voluptates sunt, excepturi tenetur at.
            </p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={design} width={100} height={100} />
            <h3 className="text-lg font-md pt-8 pb-2">Beautiful Designs</h3>
            <p className="py-2">
              Creating Elegent Designsexpedita voluptates sunt, excepturi
              tenetur at.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1">Photoshop</p>
            <p className="text-gray-800 py-1">Illustrator</p>
            <p className="text-gray-800 py-1">Adobexd</p>
            <p className="text-gray-800 py-1">Figma</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={consulting} width={100} height={100} />
            <h3 className="text-lg font-md pt-8 pb-2">Consult</h3>
            <p className="py-2">
              Creating Elegent Designsexpedita voluptates sunt, excepturi
              tenetur at.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1">Photoshop</p>
            <p className="text-gray-800 py-1">Illustrator</p>
            <p className="text-gray-800 py-1">Adobexd</p>
            <p className="text-gray-800 py-1">Figma</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={code} width={100} height={100} />
            <h3 className="text-lg font-md pt-8 pb-2">Code</h3>
            <p className="py-2">
              Creating Elegent Designsexpedita voluptates sunt, excepturi
              tenetur at.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1">Photoshop</p>
            <p className="text-gray-800 py-1">Illustrator</p>
            <p className="text-gray-800 py-1">Adobexd</p>
            <p className="text-gray-800 py-1">Figma</p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Development and Designing Lorem ipsum dolor sit, amet consectetur
              a dipisicing elit.
              <span className="text-teal-500">
                Dolorum q uod expedita ullam laborum eligendi nulla
              </span>
              a illum, ducimus eveniet iusto consequatur quia! Illum ut expedita
              voluptates sunt, excepturi tenetur at.
            </p>
          </div>
          <div>
            <div>
              <Image src={web1} />
            </div>
            <div>
              <Image src={web2} />
            </div>
            <div>
              <Image src={web3} />
            </div>
            <div>
              <Image src={web4} />
            </div>
            <div>
              <Image src={web5} />
            </div>
            <div>
              <Image src={web6} />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
